In [2]:
import numpy as np
import pandas as pd
import plotly.express as px
from ydata_profiling import ProfileReport

In [3]:
data = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

# EDA

In [4]:
#read all columns
pd.set_option('display.max_columns', None)
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [5]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB
None

In [6]:
data.describe(include='all')

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
count,1460.000000,1460.000000,1460,1201.000000,1460.000000,1460,91,1460,1460,1460,1460,1460,1460,1460,1460,1460,1460,1460.000000,1460.000000,1460.000000,1460.000000,1460,1460,1460,1460,588,1452.000000,1460,1460,1460,1423,1423,1422,1423,1460.000000,1422,1460.000000,1460.000000,1460.000000,1460,1460,1460,1459,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460,1460.000000,1460,1460.000000,770,1379,1379.000000,1379,1460.000000,1460.000000,1379,1379,1460,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,7,281,54,1460.000000,1460.000000,1460.000000,1460,1460,1460.000000
unique,NaN,NaN,5,NaN,NaN,2,2,4,4,2,5,3,25,9,8,5,8,NaN,NaN,NaN,NaN,6,8,15,16,3,NaN,4,5,6,4,4,4,6,NaN,6,NaN,NaN,NaN,6,5,2,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,7,NaN,5,6,NaN,3,NaN,NaN,5,5,3,NaN,NaN,NaN,NaN,NaN,NaN,3,4,4,NaN,NaN,NaN,9,6,NaN
top,NaN,NaN,RL,NaN,NaN,Pave,Grvl,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,NaN,NaN,NaN,NaN,Gable,CompShg,VinylSd,VinylSd,BrkFace,NaN,TA,TA,PConc,TA,TA,No,Unf,NaN,Unf,NaN,NaN,NaN,GasA,Ex,Y,SBrkr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TA,NaN,Typ,NaN,Gd,Attchd,NaN,Unf,NaN,NaN,TA,TA,Y,NaN,NaN,NaN,NaN,NaN,NaN,Gd,MnPrv,Shed,NaN,NaN,NaN,WD,Normal,NaN
freq,NaN,NaN,1151,NaN,NaN,1454,50,925,1311,1459,1052,1382,225,1260,1445,1220,726,NaN,NaN,NaN,NaN,1141,1434,515,504,445,NaN,906,1282,647,649,1311,953,430,NaN,1256,NaN,NaN,NaN,1428,741,1365,1334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,735,NaN,1360,NaN,380,870,NaN,605,NaN,NaN,1311,1326,1340,NaN,NaN,NaN,NaN,NaN,NaN,3,157,49,NaN,NaN,NaN,1267,1198,NaN
mean,730.500000,56.897260,NaN,70.049958,10516.828082,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.099315,5.575342,1971.267808,1984.865753,NaN,NaN,NaN,NaN,NaN,103.685262,NaN,NaN,NaN,NaN,NaN,NaN,NaN,443.639726,NaN,46.549315,567.240411,1057.429452,NaN,NaN,NaN,NaN,1162.626712,346.992466,5.844521,1515.463699,0.425342,0.057534,1.565068,0.382877,2.866438,1.046575,NaN,6.517808,NaN,0.613014,NaN,NaN,1978.506164,NaN,1.767123,472.980137,NaN,NaN,NaN,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,NaN,NaN,NaN,43.489041,6.321918,2007.815753,NaN,NaN,180921.195890
std,421.610009,42.300571,NaN,24.284752,9981.264932,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.382997,1.112799,30.202904,20.645407,NaN,NaN,NaN,NaN,NaN,181.066207,NaN,NaN,NaN,NaN,NaN,NaN,NaN,456.098091,NaN,161.319273,441.866955,438.705324,NaN,NaN,NaN,NaN,386.587738,436.528436,48.623081,525.480383,0.518911,0.238753,0.550916,0.502885,0.815778,0.220338,NaN,1.625393,NaN,0.644666,NaN,NaN,24.689725,NaN,0.747315,213.804841,NaN,NaN,NaN,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,NaN,NaN,NaN,496.123024,2.703626,1.328095,NaN,NaN,79442.502883
min,1.000000,20.000000,NaN,21.000000,1300.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1872.000000,1950.000000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,334.000000,0.000000,0.000000,334.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,2.000000,NaN,0.000000,NaN,NaN,1900.000000,NaN,0.000000,0.000000,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,0.000000,1.000000,2006.000000,NaN,NaN,34900.000000
25%,365.750000,20.000000,NaN,59.000000,7553.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,5.000000,1954.000000,1967.000000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000,223.000000,795.750000,NaN,NaN,NaN,NaN,882.000000,0.000000,0.000000,1129.500000,0.000000,0.000000,1.000000,0.000000,2.000000,1.000000,NaN,5.000000,NaN,0.000000,NaN,NaN,1961.000000,NaN,1.000000,334.500000,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,0.000000,5.000000,2007.000000,NaN,NaN,129975.000000
50%,730.500000,50.000000,NaN,69.000000,9478.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,5.000000,1973.000000,1994.000000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,383.500000,NaN,0.000000,477.500000,991.500000,NaN,NaN,NaN,NaN,1087.000000,0.000000,0.000000,1464.000000,0.000000,0.000000,2.000000,0.000000,3.000000,1.000000,NaN,6.000000,NaN,1.000000,NaN,NaN,1980.000000,NaN,2.000000,480.000000,NaN,NaN,NaN,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,0.000000,6.000000,2008.000000,NaN,NaN,163000.000000
75%,1095.250000,70.000000,NaN,80.000000,11601.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,6.000000,2000.000000,2004.000000,NaN,NaN,NaN,NaN,NaN,166.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,712.250000,NaN,0.000000,808.000000,1298.250000,NaN,NaN,NaN,NaN,1391.250000,728.000000,0.000000,1776.750000,1.000000,0.000000,2.000000,1.000000,3.000000,1.000000,NaN,7.000000,NaN,1.000000,NaN,NaN,2002.000000,NaN,2.000000,576.000000,NaN,NaN,NaN,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,0.000000,8.000000,2009.000000,NaN,NaN,214000.000000
max,1460.000000,190.000000,NaN,313.000000,215245.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,9.000000,2010.000000,2010.000000,NaN,NaN,NaN,NaN,NaN,1600.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5644.000000,NaN,1474.000000,2336.000000,6110.000000,NaN,NaN,NaN,NaN,4692.000000,2065.000000,572.000000,5642.000000,3.000000,2.000000,3.000000,2.000000,8.000000,3.000000,NaN,14.000000,NaN,3.000000,NaN,NaN,2010.000000,NaN,4.000000,1418.000000,NaN,NaN,NaN,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,NaN,NaN,NaN,15500.000000,12.000000,2010.000000,NaN,NaN,755000.000000

In [7]:
data["house_Age"]=data["YrSold"]-data["YearBuilt"]

In [ ]:
Numi_col= list(set(data.select_dtypes([float,int]).columns))
non_needed_features=["Id",'MoSold','YearRemodAdd','YrSold','YearBuilt',"GarageYrBlt"]
for i in non_needed_features:
    if i in Numi_col:
        Numi_col.remove(i)
print(Numi_col)

['WoodDeckSF', 'MSSubClass', 'LowQualFinSF', 'BsmtUnfSF', 'BsmtHalfBath', 'HalfBath', 'KitchenAbvGr', 'SalePrice', 'BsmtFullBath', 'BsmtFinSF1', '2ndFlrSF', 'FullBath', 'GarageCars', 'GarageArea', 'PoolArea', 'OpenPorchSF', 'GrLivArea', 'BedroomAbvGr', 'MasVnrArea', 'OverallQual', '3SsnPorch', 'house_Age', 'TotalBsmtSF', 'ScreenPorch', '1stFlrSF', 'LotFrontage', 'BsmtFinSF2', 'Fireplaces', 'EnclosedPorch', 'MiscVal', 'LotArea', 'OverallCond', 'TotRmsAbvGrd']

In [9]:
Cati_col = list(set(data.select_dtypes(object)))
print(Cati_col)

['MSZoning', 'BsmtCond', 'BsmtFinType1', 'BldgType', 'HeatingQC', 'LotConfig', 'LandContour', 'Heating', 'GarageType', 'Condition2', 'Alley', 'Electrical', 'Fence', 'BsmtQual', 'CentralAir', 'GarageFinish', 'SaleCondition', 'BsmtFinType2', 'Foundation', 'Exterior2nd', 'FireplaceQu', 'Utilities', 'PavedDrive', 'PoolQC', 'BsmtExposure', 'ExterCond', 'RoofStyle', 'LotShape', 'RoofMatl', 'KitchenQual', 'GarageCond', 'Exterior1st', 'ExterQual', 'Condition1', 'Neighborhood', 'GarageQual', 'MiscFeature', 'LandSlope', 'MasVnrType', 'Street', 'HouseStyle', 'Functional', 'SaleType']

## Report numeric features

In [10]:
# # report Numi_col
# numi_rep = ProfileReport(data[Numi_col], title="Numi_col Report" , minimal=True)

# rep=numi_rep.to_notebook_iframe()
# rep

##### correlation check

In [11]:
corr_matrix= data[Numi_col].corr(method="spearman")
#used Spearman correlation method because the data has outliers

In [12]:
px.imshow(corr_matrix,
                width=1200,height=800,
                color_continuous_scale=px.colors.sequential.RdBu , zmin=-.75,zmax=.75)

In [13]:
#filter correlation matrix
corr_over7 = corr_matrix[(corr_matrix >= 0.7) & (corr_matrix < 1)]

In [14]:
px.imshow(corr_over7,
                width=1200,height=800,
            )

###### now we will drop features that : 
have high correlation with other features over 70%, keep the high correlated with target and drop the another one 
            ['1stFlrSF', 'GarageArea', 'TotRmsAbvGrd' ]

In [15]:
features_to_delete = ['1stFlrSF', 'GarageArea', 'TotRmsAbvGrd' ]
for i in features_to_delete:
    Numi_col.remove(i)

In [16]:
print (len(Numi_col), Numi_col)

30 ['WoodDeckSF', 'MSSubClass', 'LowQualFinSF', 'BsmtUnfSF', 'BsmtHalfBath', 'HalfBath', 'KitchenAbvGr', 'SalePrice', 'BsmtFullBath', 'BsmtFinSF1', '2ndFlrSF', 'FullBath', 'GarageCars', 'PoolArea', 'OpenPorchSF', 'GrLivArea', 'BedroomAbvGr', 'MasVnrArea', 'OverallQual', '3SsnPorch', 'house_Age', 'TotalBsmtSF', 'ScreenPorch', 'LotFrontage', 'BsmtFinSF2', 'Fireplaces', 'EnclosedPorch', 'MiscVal', 'LotArea', 'OverallCond']

#### check for missing values

##### missing values

In [19]:
# check how many rows with missig values from 1460 rows
rows_with_nan = data[Numi_col].isna().any(axis=1).sum()
print(rows_with_nan)
print(f"{rows_with_nan/1460*100:.2f}% of rows with missing values")

265
18.15% of rows with missing values

##### we will impute the missing values in 'LotFrontage' with the Mean of the column as in had 259 missing values most of the nulls 
 then we will drop rest of numeric features with missing values

In [20]:
data['LotFrontage']=data['LotFrontage'].fillna(70)

In [26]:
data[Numi_col].dropna().info()

<class 'pandas.core.frame.DataFrame'>
Index: 1452 entries, 0 to 1459
Data columns (total 30 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   WoodDeckSF     1452 non-null   int64
 1   MSSubClass     1452 non-null   int64
 2   LowQualFinSF   1452 non-null   int64
 3   BsmtUnfSF      1452 non-null   int64
 4   BsmtHalfBath   1452 non-null   int64
 5   HalfBath       1452 non-null   int64
 6   KitchenAbvGr   1452 non-null   int64
 7   SalePrice      1452 non-null   int64
 8   BsmtFullBath   1452 non-null   int64
 9   BsmtFinSF1     1452 non-null   int64
 10  2ndFlrSF       1452 non-null   int64
 11  FullBath       1452 non-null   int64
 12  GarageCars     1452 non-null   int64
 13  PoolArea       1452 non-null   int64
 14  OpenPorchSF    1452 non-null   int64
 15  GrLivArea      1452 non-null   int64
 16  BedroomAbvGr   1452 non-null   int64
 17  MasVnrArea     1452 non-null   float64
 18  OverallQual    1452 non-null   int64
 19  3SsnPorch      1452 non-null   int64
 20  house_Age      1452 non-null   int64
 21  TotalBsmtSF    1452 non-null   int64
 22  ScreenPorch    1452 non-null   int64
 23  LotFrontage    1452 non-null   float64
 24  BsmtFinSF2     1452 non-null   int64
 25  Fireplaces     1452 non-null   int64
 26  EnclosedPorch  1452 non-null   int64
 27  MiscVal        1452 non-null   int64
 28  LotArea        1452 non-null   int64
 29  OverallCond    1452 non-null   int64
dtypes: float64(2), int64(28)
memory usage: 351.7 KB

#### outliers

In [22]:
small_scale = ['WoodDeckSF', 'MSSubClass', 'LowQualFinSF', 'BsmtUnfSF', 'BsmtHalfBath', 'HalfBath', 'KitchenAbvGr',  'BsmtFullBath', 'BsmtFinSF1', '2ndFlrSF', 'FullBath', 'GarageCars', 'PoolArea', 'OpenPorchSF', 'GrLivArea', 'BedroomAbvGr', 'MasVnrArea', 'OverallQual', '3SsnPorch', 'house_Age', 'TotalBsmtSF', 'ScreenPorch', 'LotFrontage', 'BsmtFinSF2', 'Fireplaces', 'EnclosedPorch', 'MiscVal', 'OverallCond']
large_scale=['SalePrice', 'LotArea']
 
graphoutliers = px.box(data[small_scale], orientation= 'h' , height= 800) 
graphoutliers.show()

In [24]:
graphoutliers2 = px.box(data[large_scale], orientation='h' )
graphoutliers2.show()

## now we can say we have 30 Numerical Features ready to enter the Pipeline phase

## report catagorical features

In [ ]:
# #cati_col
# cati_rep = ProfileReport(data[Cati_col], title="Cati_col Report" ,minimal=True)

# rep2= cati_rep.to_notebook_iframe()
# rep2

# EDA insights
we have 37 numeric features and 43 categorical features 
the categorical features needs to be splited into ordinal and nominal features

numeric features processing:
some unnecesary features were dropped (["Id",'MoSold','YearRemodAdd','YrSold','YearBuilt',"GarageYrBlt"]) I made house_age feature insteed

Missing: we imputed the missing values (['LotFrontage']) with the mean of the column 

multicollinearity: we dropped 3 features (["TotalBsmtSF","GarageArea","1stFlrSF"])

Zeros: The high number of zeros is normal for features like PoolArea or 2ndFlrSF, as most houses don't have them. This is often fine




catigorical features processing:

data needs imputation missing = none then zero

split to ordinal (['ExterQual', 'ExterCond', 'BsmtQual', 'BsmtCond', 'HeatingQC', 'KitchenQual', 'FireplaceQu', 'GarageQual', 'GarageCond', 'LandSlope', 'LotShape', 'PavedDrive'])
as the values are for quality evaluation and will be ordenaly encoded as int: 
 5      Ex	Excellent
 4      Gd	Good
 3      TA	Typical/Average
 2      Fa	Fair
 1      Po	Poor
 0      NA none

the rest are nominal will be hot encoded

like this we can avoide the curse of dimensionality